WeatherFirstCommit
junaidsaleem-arbisoft/React pull request #2
Opened 2021-10-26 06:51 UTC by junaidsaleem-arbisoft

2021-10-29 09:37 UTC, Fiju requested changes
- Move all static assets in a new directory called `assets`
- Component file names should be using camel case conventions
- Move all sensitive information in environment variables. [Docs](https://create-react-app.dev/docs/adding-custom-environment-variables/)
- Consider using functional components using hooks to get familiar with latest practices

2021-11-04 08:23 UTC, Fiju requested changes
- Configure prettier in your project and hook it with pre-commit hook

2021-11-04 08:23 UTC, Fiju commented on .env
> +DOMAIN=http://dataservice.accuweather.com
Is this variables accessible? I think React environment variables need to start with `REACT_APP`

2021-11-04 08:23 UTC, Fiju commented on src/components/ChartComponent.js
> +function chart(props) {
Component names should start with capital letter.

2021-11-04 08:23 UTC, Fiju commented on src/components/WeatherComponent.js
> +                });
Can't we avoid this approach? This is generally not preffered

2021-11-04 08:23 UTC, Fiju commented on src/components/WeatherComponent.js
> +            },
Move all the logical work on data to a normalizer function.

2021-11-04 08:23 UTC, Fiju commented on src/components/WeatherComponent.js
> +            const data = await this.getDataService(process.env.REACT_APP_CITY_URL, value, process.env.REACT_APP_CITY_PARAM)
Instead of accessing environment variables multiple time. Make a new file and move all the environment variables and access them through that file

2021-11-04 08:23 UTC, Fiju commented on src/components/WeatherComponent.js
> +    async handleInputChange(value) {
Any specific reason we are using async approach? We should avoid making asynchronous operations synchronous

2021-11-04 10:51 UTC, junaidsaleem-arbisoft commented on .env
> +DOMAIN=http://dataservice.accuweather.com
I have used it in further environment variables like 
DOMAIN=http://dataservice.accuweather.com
REACT_APP_CITY_URL=$DOMAIN/locations/v1/cities/search/?q=

2021-11-04 11:05 UTC, junaidsaleem-arbisoft commented on src/components/WeatherComponent.js
> +    async handleInputChange(value) {
Actually we are calling the api here and the input changes so frequently that if we don't wait for the api to load, on some input changes the data gets lost.

2021-11-04 11:42 UTC, Fiju approved these changes
Configure prettier in the project

2021-11-04 20:14 UTC, merged